config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  resources :patients do
    resources :pains
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pain.rb
class Pain < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :scale
  belongs_to :patient

  validates :pain_scale_id, numericality: { other_than: 0, message: "can't be blank" }

  with_options presence: true do
    validates :pain_scale_id
    validates :pain_part
    validates :time
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :pains, dependent: :destroy

  with_options presence: true do
    validates :patient_name
  end
end

app/models/scale.rb
class Scale < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '0：痛みがない' },
    { id: 2, name: '1：ほんの少し痛い' },
    { id: 3, name: '2：少し痛い' },
    { id: 4, name: '3：もっと痛い' },
    { id: 5, name: '4：かなり痛い' },
    { id: 6, name: '5：耐えられないくらい痛い' },
  ]

  include ActiveHash::Associations
  has_many :pains
end

app/models/user.rb
class User < ApplicationRecord
  has_many :patients
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :user_name,           presence: true
  validates :password,            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/pains_controller.rb
class PainsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_pain, only: [:edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def new
    @pain = Pain.new
  end

  def create
    @pain = Pain.new(pain_params)
    if @pain.save
      redirect_to patient_path(@patient)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @pain.update(pain_params)
      redirect_to patient_path(@patient)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pain.destroy
    redirect_to patient_path(@patient)
  end

  private

  def set_patient
    @patient = Patient.find(params[:patient_id])
  end

  def set_pain
    @pain = @patient.pains.find(params[:id])
  end

  def authorize_user!
    redirect_to root_path, alert: '権限がありません' unless @patient.user == current_user
  end

  def pain_params
    params.require(:pain).permit(:time, :pain_part, :pain_scale_id, :treatment, :evaluation, :memo).merge(patient_id: params[:patient_id])
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_exist_patients, only: :index
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patients_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @pains = @patient.pains.order(time: :desc)
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to patient_path
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end


  private

  def patient_params
    params.require(:patient).permit(:patient_name).merge(user_id: current_user.id)
  end

  def check_exist_patients
    @patients = current_user.patients.order(patient_name: :asc)
    redirect_to new_patient_path if @patients.empty?
  end

  def set_patient
    @patient = current_user.patients.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pains_helper.rb
module PainsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/top.html.erb
<%= render "shared/header" %>
<h1>トップページ</h1>
<%= link_to "患者さん一覧", patients_path, class: "button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PainScale</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
    </header>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>

app/views/pains/edit.html.erb
<%= render "shared/header" %>
<div class="pain-contents">

  <%# 痛み入力フォーム %>
  <div class="add-pain-main">
    <h2 class="add-pain-title">
      <%=@patient.patient_name%>さんの痛みの記録を編集
    </h2>

    <%# ペインスケール画像 %>
    <div class="pain-scale-img">
    <%= image_tag "pain_scale.jpg", class:"pain-scale", size: "350x100" %>
    </div>
    <%# ペインスケール画像 %>

    <%= form_with model: [@patient, @pain], local: true do |f| %>
      <div class="pain-date-text">
        痛みがあった日時
      </div>
      <%= f.datetime_field :time, class:"time", placeholder:"時刻" %>

      <div class="pain-treatment-text">
        痛みの部位
      </div>
      <%= f.text_area :pain_part, class:"pain_partt", placeholder:"痛みのある場所を記載してください", style: "width: 350px;" %>

      <div class="pain-level-text">
        痛みのつよさ
      </div>
      <%= f.collection_select(:pain_scale_id, Scale.all, :id, :name, {}, {class:"scale-select"}) %>

      <div class="pain-treatment-text">
        痛みに対する処置
      </div>
      <%= f.text_area :treatment, class:"treatment", placeholder:"痛みに対して行った処置があれば記載してください", style: "width: 350px;" %>

      <div class="pain-evaluation-text">
        痛みに対する処置の効果
      </div>
      <%= f.text_area :evaluation, class:"evaluation", placeholder:"処置を行った後の効果があれば記載してください", style: "width: 350px;" %>

      <div class="pain-memo-text">
        その他痛みに関してメモ
      </div>
      <%= f.text_area :memo, class:"memo", placeholder:"気になったことがあれば記載してください", style: "width: 350px;" %>
      <%= f.submit "痛みを更新" ,class:"btn" %>
    <% end %>
  </div>
  <%# 痛み入力フォーム %>
</div>

app/views/pains/new.html.erb
<%= render "shared/header" %>
<div class="pain-contents">

  <%# 痛み入力フォーム %>
  <div class="add-pain-main">
    <h2 class="add-pain-title">
      <%=@patient.patient_name%>さんの痛みの記録を入力
    </h2>

    <%# ペインスケール画像 %>
    <div class="pain-scale-img">
    <%= image_tag "pain_scale.jpg", class:"pain-scale", size: "350x100" %>
    </div>
    <%# ペインスケール画像 %>

    <%= form_with model: [@patient, @pain], local: true do |f| %>
      <div class="pain-date-text">
        痛みがあった日時
      </div>
      <%= f.datetime_field :time, class:"time", placeholder:"時刻" %>

      <div class="pain-treatment-text">
        痛みの部位
      </div>
      <%= f.text_area :pain_part, class:"pain_partt", placeholder:"痛みのある場所を記載してください", style: "width: 350px;" %>

      <div class="pain-level-text">
        痛みのつよさ
      </div>
      <%= f.collection_select(:pain_scale_id, Scale.all, :id, :name, {}, {class:"scale-select"}) %>

      <div class="pain-treatment-text">
        痛みに対する処置
      </div>
      <%= f.text_area :treatment, class:"treatment", placeholder:"痛みに対して行った処置があれば記載してください", style: "width: 350px;" %>

      <div class="pain-evaluation-text">
        痛みに対する処置の効果
      </div>
      <%= f.text_area :evaluation, class:"evaluation", placeholder:"処置を行った後の効果があれば記載してください", style: "width: 350px;" %>

      <div class="pain-memo-text">
        その他痛みに関してメモ
      </div>
      <%= f.text_area :memo, class:"memo", placeholder:"気になったことがあれば記載してください", style: "width: 350px;" %>
      <%= f.submit "痛みを記録" ,class:"btn" %>
    <% end %>
  </div>
  <%# 痛み入力フォーム %>
</div>

app/views/patients/edit.html.erb
<%= render "shared/header" %>

<div class="patient-contents">
  <div class="add-patient-main">
    <h2 class="add-patient-title">患者さん編集</h2>

    <%# ページ画像 %>
    <div class="pain-scale-img">
    <%= image_tag "family_big.png", class:"pain-scale", size: "350x200" %>
    </div>
    <%# ページ画像 %>

    <%# 患者さん登録フォーム %>
    <%= form_with model: @patient, local: true do |f| %>
      <div class="patient_name-text">
        患者さんのお名前
      </div>
      <%= f.text_area :patient_name, class:"patient_name", placeholder:"お名前を入力してください", style: "width: 350px;" %>
      <%= f.submit "患者さん更新" ,class:"btn" %>
    <% end %>
    <%# 患者さん登録フォーム %>
  </div>
</div>

app/views/patients/index.html.erb
<%= render "shared/header" %>
<h1>
<%= current_user.user_name%>さんの患者一覧
</h1>
<% @patients.each do |patient| %>
  <ul class="patients-list">
    <li class='list'>
      <%= link_to patient_path(patient) do %>
      <div class='patient-info'>
        <h3 class='patient-name-button'>
          <%= patient.patient_name %>
        </h3>
      </div>
      <% end %>
    </li>
  </ul>
<% end %>
<%= link_to "患者さん登録", new_patient_path, class: "add-patient-button" %>

app/views/patients/new.html.erb
<%= render "shared/header" %>

<div class="patient-contents">
  <div class="add-patient-main">
    <h2 class="add-patient-title">患者さん登録</h2>

    <%# ページ画像 %>
    <div class="pain-scale-img">
    <%= image_tag "family_big.png", class:"pain-scale", size: "350x200" %>
    </div>
    <%# ページ画像 %>

    <%# 患者さん登録フォーム %>
    <%= form_with model: @patient, local: true do |f| %>
      <div class="patient_name-text">
        患者さんのお名前
      </div>
      <%= f.text_area :patient_name, class:"patient_name", placeholder:"お名前を入力してください", style: "width: 350px;" %>
      <%= f.submit "患者さん登録" ,class:"btn" %>
    <% end %>
    <%# 患者さん登録フォーム %>
  </div>
</div>

app/views/patients/show.html.erb
<%= render "shared/header" %>

<%# 痛み記録一覧 %>
<div class='pain-contents'>
  <h2 class='title'>
    <%= @patient.patient_name %>さんの記録
  </h2>

  <% if current_user.id == @patient.user_id %>
    <div class='patient-actions'>
      <%= link_to '患者編集', edit_patient_path(@patient), class: 'btn edit-btn' %>
      <%= link_to '患者削除', patient_path(@patient), data: {turbo_method: :delete}, class: 'btn delete-btn' %>
    </div>
  <% end %>
 
  <%= link_to "#{@patient.patient_name}さんの痛みを登録", new_patient_pain_path(@patient), class: "add-pain-button" %>

  <ul class='pain-lists'>
    <% @pains.each do |pain| %>
      <li class='pain-list'>
        <div class='pain-info'>
          <div class='pain-header'>
            <div class='pain-time'><%= pain.time.strftime("%Y-%m-%d %H:%M") %></div>
            <h3 class='pain-part'><%= pain.pain_part %></h3>
          </div>
          <div class='pain-body'>
            <div class='pain-level'>痛みの強さ：<%= pain.pain_scale_id %></div>
          </div>
          <div class='pain-footer'>
            <div class='pain-treatment'><%= pain.treatment %></div>
            <div class='pain-evaluation'><%= pain.evaluation %></div>
            <div class='pain-memo'><%= pain.memo %></div>
          </div>
          <% if current_user == @patient.user %>
            <div class='pain-actions'>
              <%= link_to '編集', edit_patient_pain_path(@patient, pain), class: 'btn edit-btn' %>
              <%= link_to '削除', patient_pain_path(@patient, pain), data: {turbo_method: :delete}, class: 'btn delete-btn' %>
            </div>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>

  <%# 痛みがない場合のダミー表示 %>
  <% if @pains.blank? %>
    <div class='non-pain-info'>
      <h3 class='add-pain'>
        上のボタンから痛みを登録してね！
      </h3>
    </div>
  <% end %>
  <%# 痛みがない場合のダミー表示 %>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='header-left'>
    <%= link_to "Pain Record", "/" %>
  </div>
  <div class='header-right'>
    <% if user_signed_in? %>
      <div><%= link_to current_user.user_name, patients_path, class: "user-nickname" %></div>
      <div><%= link_to 'ログアウト', destroy_user_session_path, data: {turbo_method: :delete}, class: "logout" %></div>
    <% else %>
      <div><%= link_to 'ログイン', new_user_session_path, class: "login" %></div>
      <div><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></div>
    <% end %>
  </div>
</header>